services:
  ###> PostgreSQL ###
  postgres:
    env_file:
      - .env.docker
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432"

  ###> PHP-FPM ###
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - postgres
    environment:
      PHP_IDE_CONFIG: "serverName=symfony-app"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ###> SphinxSearch ###
  sphinx:
    image: macbre/sphinxsearch
    container_name: sphinx
    ports:
      - "9306:9306"
      - "9312:9312"
    volumes:
      - ./docker/sphinx:/etc/sphinxsearch
      - ./docker/sphinx:/opt/sphinx/conf
      - ./sphinx_data:/var/lib/sphinx
    depends_on:
      - postgres
    command: sh -c "indexer --all --config /opt/sphinx/conf/sphinx.conf && searchd --nodetach --config /opt/sphinx/conf/sphinx.conf"

  ###> Nginx ###
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ###> NodeJs ###
  node:
    image: node:20.16.0-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - php-fpm
    command: sh -c "while sleep 3600; do :; done"

volumes:
  postgres_data:
