# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.dadata_token: '%env(APP_DADATA_TOKEN)%'

services:
    security.authentication.success_handler:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler


    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $dadataToken: '%env(APP_DADATA_TOKEN)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ManagerService:
        calls:
            - method: setCompanyService
              arguments:
                  - '@App\Service\CompanyService'

    App\Service\CompanyHistoryService:
        calls:
            - method: setCompanyService
              arguments:
                  - '@App\Service\CompanyService'

    App\Service\SphinxSearchService:
        arguments:
            $host: '%env(SPHINX_HOST)%'
            $port: '%env(int:SPHINX_PORT)%'
            $db: '%env(SPHINX_DB)%'
